begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'bundler/gem_helper'
Bundler::GemHelper.install_tasks name: 'kit_demo-main'

require_relative 'config/kit_runtime_config'
require 'kit/dummy-app-container/rails_application'

APP_RAKEFILE = File.expand_path('spec/dummy/Rakefile', __dir__)
load 'rails/tasks/engine.rake'

Rails.application.load_tasks

require 'seedbank'
Seedbank.seeds_root = File.expand_path('db/seeds', __dir__)
Seedbank.load_tasks if defined?(Seedbank)
